# Generated by Django 3.1.1 on 2026-04-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20260427_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='test',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='studentresult',
            name='marks_obtained',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='total_marks',
            field=models.FloatField(default=100),
        ),
    ]
