# Generated by Django 3.1.1 on 2026-04-27 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.course'),
        ),
        migrations.AddField(
            model_name='notice',
            name='is_global',
            field=models.BooleanField(default=True),
        ),
    ]
