# Generated by Django 3.1.1 on 2026-04-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_assignment_birthday_dailyfeecollection_event_examform_facultyleave_fee_news_settings_syllabus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
